# Generated by Django 5.2.1 on 2025-05-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_photograph_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
