# Generated by Django 5.2.1 on 2025-05-14 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_photograph_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
